# Generated by Django 3.0.3 on 2020-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_id',
            field=models.CharField(max_length=20),
        ),
    ]
